### PR TITLE
stop react to every message starting with a comma

### PR DESCRIPTION
**Pull request by SuperOP535**
merge this kthxbye

### CODE REVIEW

**Comment by Thunder33345** [comment]
bad
bad bad!!!

**Comment by SuperOP535** [comment]
why bad
why bad bad???

**Comment by HimbeersaftLP** [comment]
Funfact: It only does this on the BOD Discord

**Comment by SuperOP535** [comment]
Funfact: I know that

**Comment by HimbeersaftLP** [comment]
Funfact: I won't merge

**Comment by HimbeersaftLP** [comment]
Funfact: I'll merge if you'd make it so it only reacts to known commands with the hourglass

**Comment by SuperOP535** [comment]
Funfact: Okay I will do my best

**Comment by SuperOP535** [comment]
Funfact: I'm closing this now and I'm gonna fork now.

**Pull request closed without merging**
