### PR TITLE
Stop the bot from reacting to unknown commands

### PR DESCRIPTION
**Pull request by SuperOP535**
merge this kthx

### CODE REVIEW

**Comment by Thunder33345** [comment]
close!!!!!!!
duplicate of #2

**Comment by SuperOP535** [comment]
If you are not ok with this I just remembered a much simpler solution so tell me if you want me to improve it

**Comment by Thunder33345** [comment]
well you could just improved upon #2 rather then reopening a new one

**Comment by SuperOP535** [comment]
well i'm not used to pull request stuff cuz i don't really use github that much

**Comment by HimbeersaftLP** [comment]
If that makes you happy @SuperOP535

**Comment by nathfreder** [comment]
@SuperOP535 GitHub is not GIT!

**Comment by SuperOP535** [comment]
@nathfreder ik?

**Comment by TheRoyalBlock** [comment]
Do you know? DO you really?

**Comment by Thunder33345** [comment]
git gud

**Pull request merged**
