### PR TITLE
Dis allow everyone/here pings on ,say

### PR DESCRIPTION
**Pull request by JaxkDev**
Self explanatory really...

### CODE REVIEW

**Comment by HBIDamian** [comment]
I don’t see any point of this anyway tbh, as people still get the notifications for the initial command. ¯\_(ツ)_/¯ 

All you’re doing is stopping double notification

**Comment by JaxkDev** [comment]
If the user does not have perms to ping but sends the test @ everyone the bot could ping it, himbeersaftLP also added the check for that

**Comment by HimbeersaftLP** [comment]
@HBIDamian Apparently there is a Discord bug that let's the bot still mention everyone and here even if it doesn't have that permission.

I haven't tested that, but I added this just in case.

At the event of the heat death of the universe (= when the rewrite will be finished) I might add an option for this.

**Comment by Thunder33345** [comment]
i thought we are taking a stance of "this is intended"?

**Comment by HimbeersaftLP** [comment]
It would be, if it weren't for that apparent Discord bug

**Comment by nathfreder** [comment]
I don't get this PR but ok

**Pull request merged**
